# Generated by Django 2.2.12 on 2020-06-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='addressDetail',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
